drop
database if exists DBRegistroVerificacao;
create
database DBRegistroVerificacao;
use
DBRegistroVerificacao;

CREATE TABLE CARGO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE NIVELACESSO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE STATUSUSUARIO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE USUARIO
(
    ID            INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME          VARCHAR(255),
    CPF           VARCHAR(11),
    TELEFONE      VARCHAR(11),
    DATANASCIMENTO  DATE,
    CTPS          VARCHAR(11) UNIQUE,
    IDNIVELACESSO INT,
    FOREIGN KEY (IDNIVELACESSO) REFERENCES NIVELACESSO (ID),
    IDCARGO INT,
    FOREIGN KEY (IDCARGO) REFERENCES CARGO (ID),
	MATRICULA 	  NUMERIC(6) UNIQUE,
    SENHA 		  VARCHAR(55),
    IDSTATUSUSUARIO INT,
    FOREIGN KEY (IDSTATUSUSUARIO) REFERENCES STATUSUSUARIO (ID),
    IDULTIMOAFASTAMENTO INT,
    DATACONTRATACAO DATE,
    DATADESLIGAMENTO DATE
);

CREATE TABLE AFASTAMENTO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NATUREZA VARCHAR(255),
    DESCRICAO VARCHAR(255),
    DATAINICIO DATE,
    DATAFIM DATE,
    IDUSUARIO INT,
    FOREIGN KEY (IDUSUARIO)
        REFERENCES USUARIO (ID)
);

CREATE TABLE ATIVIDADE
(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO     VARCHAR(255),
    IDCARGO   INT,
    FOREIGN KEY (IDCARGO) REFERENCES CARGO (ID)
);

CREATE TABLE SALA
(
    ID         INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NUMERO     VARCHAR(10),
    DISPONIVEL BOOLEAN
);

CREATE TABLE SERVICOPRESTADO
(
    ID            INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IDSALA        INT,
    FOREIGN KEY (IDSALA) REFERENCES SALA (ID),
    DATAINICIO    DATETIME,
    DATAFIM       DATETIME,
    IDUSUARIO INT,
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (ID),
    IDATIVIDADE INT,
    FOREIGN KEY (IDATIVIDADE) REFERENCES ATIVIDADE (ID),
    IDOCORRENCIA INT
);

CREATE TABLE OCORRENCIA (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(255),
    CATEGORIA VARCHAR (255),
    STATUSOCORRENCIA BOOLEAN,
    DATAOCORRENCIA    DATETIME,
    IDSERVICOPRESTADO INT,
    FOREIGN KEY (IDSERVICOPRESTADO)
        REFERENCES SERVICOPRESTADO (ID)
);

/*NIVEIS DE ACESSO*/
INSERT INTO NIVELACESSO (descricao)
VALUES ('FUNCIONARIO');

INSERT INTO NIVELACESSO (descricao)
VALUES ('RH');

INSERT INTO NIVELACESSO (descricao)
VALUES ('GERENCIA');

/*CARGOS*/
INSERT INTO CARGO (descricao)
VALUES ('FAXINA');

INSERT INTO CARGO (descricao)
VALUES ('ZELADORIA');

INSERT INTO CARGO (descricao)
VALUES ('TECNICO');

INSERT INTO CARGO (descricao)
VALUES ('RH');

INSERT INTO CARGO (descricao)
VALUES ('GERENCIA');

/*STATUSUSUARIO*/
INSERT INTO STATUSUSUARIO (descricao)
VALUES ('ATIVO');

INSERT INTO STATUSUSUARIO (descricao)
VALUES ('INATIVO');

INSERT INTO STATUSUSUARIO (descricao)
VALUES ('AFASTADO');

/*SALAS*/
INSERT INTO SALA (numero, disponivel)
VALUES (101, TRUE);
INSERT INTO SALA (numero, disponivel)
VALUES (102, TRUE);
INSERT INTO SALA (numero, disponivel)
VALUES (103, TRUE);
INSERT INTO SALA (numero, disponivel)
VALUES (201, TRUE);
INSERT INTO SALA (numero, disponivel)
VALUES (202, TRUE);

SELECT 
    U.ID AS idUsuario,
    U.NOME AS nomeUsuario,
    C.descricao AS cargo,
    S.ID AS idSala,
    S.NUMERO AS numeroSala,
    SP.DATAINICIO AS dataInicio,
    SP.DATAFIM AS dataFim,
    A.DESCRICAO AS atividade,
    O.DESCRICAO AS ocorrencia
FROM
    USUARIO U,
    CARGO C,
    SALA S,
    SERVICOPRESTADO SP,
    ATIVIDADE A,
    OCORRENCIA O
WHERE
    SP.IDUSUARIO = U.ID AND C.ID = U.IDCARGO
        AND S.ID = SP.IDSALA;